## Parameter settings for demo.
source_dir: './data/benchmark/weather'
## If you want to use other source files as a stream, you can fill in filenames below.
source_files: 
  - 'GR'
  - 'NO'
  - 'DE'
## Define '# of Steps'
anomaly_step:
  - num_intervals: 1
    gap_size: 3000
  - num_intervals: 2
    gap_size: 2000

## Define all types of Anomaly
anomaly_params:
## 1st step: one-interval (point)
  - type: 'point'
    distribution: 'uniform'
    upperbound: 0.5
    lowerbound: -0.5
    percentage: 0.01
    num_values: 100
## 2nd step: for 2-intervals 
  ## (1) 1st interval (collective) 
  - type: 'collective'
    distribution: 'gaussian'
    mu: 1
    sigma: 0.1
    percentage: 0.01
    num_values: 50
    length: 6
  ## (2) 2nd interval (sequential)
  - type: 'periodic'
    noise_factor: 0.5
    start: 2232 ## 24*31*3
    percentage: 0.05
    length: 24
## Drift params
moa_path: '../moa-release-2023.04.0/lib'
drift_dir: '/data/synthetic'
drift_params:
  n_drift: 5
  p_drift: 0.01
  p_before: 0.1
  sub_dir: 'demo'